language: julia
julia:
    - 1.0
    - nightly
sudo: required
dist: trusty

notification: 
    email: false

before_install:
    - wget -q -O /tmp/install-icc.sh "https://raw.githubusercontent.com/sunoru/julia-icc-travis/master/install-icc.sh"
    - chmod 755 /tmp/install-icc.sh
    - sudo /tmp/install-icc.sh --components mkl --dest /opt/intel --tmpdir /root/tmp || exit 1
    # only install mkl
    - . ~/.bashrc

script:
    - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.test("VSL", coverage=true)'

after_success:
    - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
